import { defineType, defineField } from "sanity";

/** Curso. */
export const course = defineType({
  name: "course",
  title: "Curso",
  type: "document",
  groups: [
    { name: "conteudo", title: "Conteúdo", default: true },
    { name: "detalhe", title: "Página de detalhe" },
    { name: "datas", title: "Datas" },
  ],
  fields: [
    defineField({
      name: "orderRank",
      title: "Ordem",
      type: "number",
      description: "Define a ordem na listagem (menor aparece primeiro).",
      group: "conteudo",
      initialValue: 0,
    }),
    defineField({
      name: "title",
      title: "Título",
      type: "string",
      group: "conteudo",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      group: "conteudo",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "subtitle",
      title: "Subtítulo",
      type: "string",
      group: "conteudo",
    }),
    defineField({
      name: "category",
      title: "Categoria",
      type: "string",
      group: "conteudo",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "summary",
      title: "Resumo",
      type: "text",
      rows: 3,
      description: "Frase curta — usada na listagem e nos metadados.",
      group: "conteudo",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "audience",
      title: "Para quem",
      type: "text",
      rows: 2,
      group: "conteudo",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "image",
      title: "Imagem",
      type: "figure",
      group: "conteudo",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "outcomes",
      title: "Resultados (listagem)",
      type: "array",
      of: [{ type: "string" }],
      description: "3–4 resultados concretos apresentados no cartão.",
      group: "conteudo",
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: "duration",
      title: "Duração",
      type: "string",
      group: "detalhe",
    }),
    defineField({
      name: "schedule",
      title: "Quando",
      type: "string",
      group: "detalhe",
    }),
    defineField({
      name: "format",
      title: "Formato",
      type: "string",
      group: "detalhe",
    }),
    defineField({
      name: "includes",
      title: "O que está incluído",
      type: "array",
      of: [{ type: "string" }],
      group: "detalhe",
    }),
    defineField({
      name: "intro",
      title: "Introdução (parágrafos)",
      type: "array",
      of: [{ type: "text", rows: 3 }],
      group: "detalhe",
    }),
    defineField({
      name: "objectives",
      title: "Objetivos (o que vais aprender)",
      type: "array",
      of: [{ type: "string" }],
      group: "detalhe",
    }),
    defineField({
      name: "program",
      title: "Conteúdos programáticos",
      type: "array",
      of: [{ type: "courseModule" }],
      group: "detalhe",
    }),
    defineField({
      name: "ctas",
      title: "Botões",
      type: "array",
      of: [{ type: "cta" }],
      group: "detalhe",
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: "editions",
      title: "Edições / turmas",
      type: "array",
      of: [{ type: "courseEdition" }],
      description: "Alimenta o calendário de próximas datas.",
      group: "datas",
    }),
  ],
  orderings: [
    {
      title: "Ordem",
      name: "orderAsc",
      by: [{ field: "orderRank", direction: "asc" }],
    },
  ],
  preview: {
    select: { title: "title", subtitle: "category", media: "image" },
  },
});
