import { defineType, defineField } from "sanity";

/** Serviço. */
export const service = defineType({
  name: "service",
  title: "Serviço",
  type: "document",
  groups: [
    { name: "conteudo", title: "Conteúdo", default: true },
    { name: "detalhe", title: "Página de detalhe" },
  ],
  fields: [
    defineField({
      name: "orderRank",
      title: "Ordem",
      type: "number",
      description: "Define a ordem na listagem (menor aparece primeiro).",
      group: "conteudo",
      initialValue: 0,
    }),
    defineField({
      name: "number",
      title: "Número",
      type: "string",
      description: 'Índice de dois dígitos, ex.: "01".',
      group: "conteudo",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "title",
      title: "Título",
      type: "string",
      group: "conteudo",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      group: "conteudo",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "tag",
      title: "Etiqueta",
      type: "string",
      description: 'Pequeno qualificador, ex.: "Para atletas".',
      group: "conteudo",
    }),
    defineField({
      name: "subtitle",
      title: "Subtítulo",
      type: "string",
      group: "conteudo",
    }),
    defineField({
      name: "summary",
      title: "Resumo",
      type: "text",
      rows: 3,
      description: "Frase curta — usada na listagem e nos metadados.",
      group: "conteudo",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "description",
      title: "Descrição (listagem)",
      type: "text",
      rows: 4,
      group: "conteudo",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "image",
      title: "Imagem",
      type: "figure",
      group: "conteudo",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "audience",
      title: "Para quem",
      type: "text",
      rows: 2,
      group: "detalhe",
    }),
    defineField({
      name: "includes",
      title: "O que está incluído",
      type: "array",
      of: [{ type: "string" }],
      group: "detalhe",
    }),
    defineField({
      name: "intro",
      title: "Introdução (parágrafos)",
      type: "array",
      of: [{ type: "text", rows: 3 }],
      group: "detalhe",
    }),
    defineField({
      name: "benefits",
      title: "O que vais ganhar",
      type: "array",
      of: [{ type: "benefit" }],
      group: "detalhe",
    }),
    defineField({
      name: "process",
      title: "Como funciona",
      type: "array",
      of: [{ type: "processStep" }],
      group: "detalhe",
    }),
    defineField({
      name: "ctas",
      title: "Botões",
      type: "array",
      of: [{ type: "cta" }],
      group: "detalhe",
    }),
    defineField({
      name: "closingHeading",
      title: "CTA final — título",
      type: "string",
      group: "detalhe",
    }),
    defineField({
      name: "closingLead",
      title: "CTA final — destaque",
      type: "string",
      group: "detalhe",
    }),
    defineField({
      name: "closingBody",
      title: "CTA final — descrição",
      type: "text",
      rows: 3,
      group: "detalhe",
    }),
  ],
  orderings: [
    {
      title: "Ordem",
      name: "orderAsc",
      by: [{ field: "orderRank", direction: "asc" }],
    },
  ],
  preview: {
    select: { title: "title", subtitle: "tag", media: "image" },
  },
});
